project:
  type: website
  output-dir: docs

website:
  title: "PSYC 259: Data Science"
  navbar:
    pinned: true
    right:
      - syllabus.qmd
      - schedule.qmd
      - lectures/lectures.qmd
      - assignments.qmd
      - resources.qmd
  announcement:
    icon: calendar-check
    dismissable: true
    content: "**Reminder!** All students should fill out the ([Course Introduction Survey)](https://forms.gle/cup9GTRT8BL5UhHq8) before 1/3/24)"
    type: danger
    position: below-navbar
  
  repo-url: "https://github.com/2025-PSYC-259/course_site"
  repo-actions: [edit, issue]
  
  sidebar:
    - title: "Classes and readings"
      style: "docked"
      search: false
      background: light
      contents:
        - section: "Navigation"
          contents:
            - lectures/lectures.qmd
        - section: "Foundations"
          contents:
            - text: "1: Course Goals and Setup"
              file: lectures/1GoalsSetup.qmd
            - text: "2: R Language Basics and Importing"
              file: lectures/2Importing.qmd
        - section: "Processing"
          contents:
            - text: "3: Data Transformations"
              file: lectures/3DataTransformations.qmd
            - text: "4: Data Structure"
              file: lectures/4DataStructure.qmd          
        - section: "Efficiency"
          contents:
            - text: "5: Automation: Functions and Iteration"
              file: lectures/5Automation.qmd
            - text: "6: Exploratory Data Analysis"
              file: lectures/6EDA.qmd
        - section: "Communication"
          contents:
            - text: "7: Data Sharing and Reproducibility"
              file: lectures/7DataSharing.qmd
            - text: "8: Visualization"
              file: lectures/8Visualization.qmd              
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true




