---
title: "Week 2"
subtitle: R Language Basics and Importing
filters: 
  - webr
webr:
  packages:
    - readr
    - dplyr
    - curl
  cell-options:
    editor-font-scale: 0.8
    fig-width: 7
    fig-height: 4.3
    out-width: "100%"
---

## Slides

The slides for this week's lesson are available online as an HTML file. Use the buttons below to open the slides either as an interactive website or as a static PDF (for printing or storing for later). You can also click in the slides below and navigate through them with your left and right arrow keys.

```{r show-slide-tabs, echo=FALSE, results="asis"}
#slide_buttons("/slides/01-slides")

xaringanExtra::embed_xaringan(
  "https://psych-259-data-science-2022.github.io/259-langbasics-importing/#1",
  ratio = "16:9",
  border = "none",
  margin = "0 auto"
)
```

:::{.callout-tip}
Typing <kbd>?</kbd> (or <kbd>shift</kbd> + <kbd>/</kbd>) in the slide show brings slide navigation controls.
:::

## Practice

The `webr` block below reads one of the vocab files from a url (`read_csv` is just as happy to read a csv from the internet as from your local file system.) `head` prints the first few lines so that you can see it worked (ignore the "`curl` package not installed, falling back to using `url()`" error, it's just because we are doing this in a strange R environment in the browser rather than on your computer.)

Try some different `read_csv` options by editing the code below: 

- Use custom column names when reading in the data.
- Read in the data so that all columns are in "character" format. It will say "chr" below each column if they are in character rather than numerical format.
- Read in the data from only 13 months on

```{webr-r}
filename <- "https://raw.githubusercontent.com/psych-259-data-science-2022/259-langbasics-importing/refs/heads/master/data_cleaned/vocab_combined.csv"
vocab <- read_csv(filename)
head(vocab)
```

:::{.callout-tip}
After making your changes, Rerun the code by clicking the **{{< fa play title="Play" >}} Run Code** button. If you want to save the code you wrote, you can click *View R History" in the right panel.
:::